cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/espen/Research/A-Methodology-to-Model-the-Execution-of-Communication-Software-for-Accurate-Network-Simulation/instrumented-tinyos-plus-extended-ns3/ns-3.19/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Tools/c_config.py", line 459, in run_c_code\n    bld.compile()\n  File "/home/espen/Research/A-Methodology-to-Model-the-Execution-of-Communication-Software-for-Accurate-Network-Simulation/instrumented-tinyos-plus-extended-ns3/ns-3.19/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 139669164661200: cxx test.cpp -> test.cpp.1.o}\n[\'/usr/bin/g++\', \'-Wall\', \'-g\', \'-O0\', \'-fno-strict-aliasing\', \'-fwrapv\', \'-fstack-protector-strong\', \'-fno-strict-aliasing\', \'-I/usr/include/python2.7\', \'-DNS3_ASSERT_ENABLE\', \'-DNS3_LOG_ENABLE\', \'-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DNDEBUG\', \'-D_FORTIFY_SOURCE=2\', \'../test.cpp\', \'-c\', \'-o\', \'test.cpp.1.o\']\n'
